spring.application.name=ms-leagues
server.port=8082

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

apisports.base-url=https://v3.football.api-sports.io
apisports.key=${APISPORTS_KEY:}

jwt.secret=${JWT_SECRET:default-jwt-secret-key-default-jwt-secret-key-12345}
