spring.application.name=ms-fixtures
server.port=8085

api-sports.key=${APISPORTS_KEY:}
internal-secret=${INTERNAL_SECRET:}

football.api.free-plan=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

springdoc.api-docs.path=/api/fixtures/api-docs
springdoc.swagger-ui.path=/api/fixtures/swagger-ui.html