spring.application.name=ms-gateway
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,gateway
management.endpoint.health.show-details=always

# Info endpoint
info.app.name=SportPulse Gateway
info.app.description=API Gateway del sistema SportPulse
info.app.version=1.0.0